trigger:
  branches:
    include:
    - master
  paths:
    include:
    - RPackagesTask/*

# no PR triggers
pr: none

variables:
- group: InstallRPackages
- group: Marketplace

stages:
- template: templates/release.yml