trigger:
  branches:
    include:
    - master
  paths:
    include:
    - RScriptTask/*

# no PR triggers
pr: none

variables:
- group: RunRScript
- group: Marketplace

stages:
- template: templates/release.yml